apiVersion: v1
kind: ReplicationController
metadata:
  name: javawebapprc
  lables:
    app: javawebapp
spec:
  replicas: 2
  selector:
    app: javawebapp
  template:
    metadata:
      name: javawebapppod
      lables:
        app: javawebapp
    spec:
      containers:
      - name: javawebappcontainer
        image: dockerhandson/java-web-app:9
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javawebapprcservice
spec:
  selector:
    app: javawebapp
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32555
  type: NodePort
